// Generated by scripts/copy-mediapipe-assets.mjs (npm postinstall). Do not edit.
// The installed @mediapipe/tasks-vision version, which is also the directory the same
// script copied the runtime into under public/vendor/mediapipe/.
export const MEDIAPIPE_VERSION = "0.10.35";
